# -*- coding: utf-8 -*-
"""File_I/O.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17k-KsMV_yu6md9gWQtjhitjU5O9eGFdO
"""

with open('file.txt', 'w') as f:
  f.write('Navya is a smart smart girl\n')
  f.write('She is my pookie')
print("File created successfully!")

with open('file.txt', 'r') as f:
  content = f.read()
print(content)
f.close()

st = "Hey I am okay"
with open('file_1.txt', 'w') as f:
  f.write(st)
  f.close

with open('file_1.txt', 'r') as f:
  content = f.read()
print(content)
f.close()

with open('file.txt', 'r') as f:
  print(f.read())                     #now you don't neccessarily have to close the file

f = open("file.txt")
lines = f.readlines()
print(lines, type(lines))
f.close()

with open('poem.txt', 'w') as f:
  f.write("When life gives you tangerines, not lemons bright and sour,/n")
  f.write("Peel them slow — the sweetest things take just a little power./n")
  f.write("Let citrus light stain fingertips, a sunburst on your skin,/n")
  f.write("And taste how small, soft victories can warm the world within./n")

  f.write("Not every gift comes wrapped in gold, not every joy is loud,/n")
  f.write("Sometimes it’s just the morning light that slips beneath a cloud./n")
  f.write("So when life gives you tangerines, don’t ask for something new — /n")
  f.write("Just share their glow, and know the world tastes brighter, thanks to you.")

f = open("poem.txt")
content = f.read()
if("tangerines" in content):
  print("Yes, tangerines are present")
else:
  print("No, tangerines are not present")

s=""
f = open("hiscore.txt", "w")
f.write(s)
f.close()
#creates a new file named hiscore

import random

def game():
  print("始めましょう！")
  score = random.randint(1, 62)
  with open("hiscore.txt") as f:
      hiscore = f.read()
      if(hiscore != ""):
          hiscore = int(hiscore)
      else:
          hiscore = 0
  print(f"Your score is: {score}")
  if(score>hiscore):
      with open("hiscore.txt", "w") as f:
          f.write(str(score))
      return score
game()
#Body of the code

with open("hiscore.txt", "r") as f:
    print("Current high score:", f.read())
#reads file

def generateTable(n):
  table=""
  for i in range(1,11):
    table += f"{n} X {i} = {n*i}\n"
  with open(f"tables/table_{n}", "w") as f:
    f.write(table)

for i in range(2,21):
  generateTable(i)

with open('bad.txt', "w"):
  f.write("You are a Donkey/n")
  f.write("And you're not a bad Donkey")

word = "Donkey"
with open('bad.txt', 'r') as f:
  content = f.read()
  contentNew = content.replace(word,"#####")
with open('bad.txt', 'w') as f:
  f.write(contentNew)

words = ["Donkey","bad"]
with open('bad.txt', 'r') as f:
  content = f.read()
for word in words:
  content = content.replace(word,"#"*(len(word)))
with open('bad.txt', 'w') as f:
  f.write(content)

with open('log.txt','w') as f:
  f.write("%%html/n")
  f.write("<p>lorem435</p>")

with open('log.txt') as f:
  content = f.read()

if("python" in content):
  print("Python is present")
else:
  print("Python is not present")

with open('log.txt') as f:
  lines = f.readlines()
lineno = 1
for line in lines:
  if("python" in line):
    print(f"Python is present at line number {lineno}")
    break
  lineno += 1
else:
  print("Python is not present")

with open('this.txt','w') as f:
  f.write("Hey I'm Tam.")

with open('this.txt') as f:
  content = f.read()
with open('this_copy.txt','w') as f:
  f.write(content)

with open('this.txt') as f:
  content1 = f.read()
with open('this_copy.txt') as f:
  content2 = f.read()
  if(content1 == content2):
    print("These files are identical")
  else:
    print("These files are not identical")

with open('old.txt', 'w') as f:
  f.write("I'm 16 years old.")

with open("old.txt") as f:
  content = f.read()
with open("renamed_by_python.txt", "w") as f:
  f.write(content)