# -*- coding: utf-8 -*-
"""object_oriented_programming

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEM2tdvIcX-zCY84QRTpzGCq00l1YRrA
"""

class Employee:
  language = "Py"
  salary = 1200000                         #class attribute

harry = Employee()
harry.name = "Harry"
print(harry.language, harry.salary)          #object attribute or instance attribute

rohan = Employee()
rohan.name = "Rohan Roro Robinson"
print(rohan.name, rohan.salary, rohan.language)   #Here language and salary is class attribute and name is instance attribute

class Employee:
  language = "Py"
  salary = 1200000

harry = Employee()
harry.language = "C++"
print(harry.language, harry.salary)

"""## **Self Parameter**


"""

class Employee:
  language = "Py"
  salary = 1200000

  def getInfo(self):
    print(f"The salary is {self.salary} and the language is {self.language}")

  def greet(self):
    print("Hello")

harry = Employee()
#harry.language = "C++"
#print(harry.language, harry.salary)
#Employee.getInfo(harry)
harry.greet()
harry.getInfo()

"""# **Static Method**"""

class Employee:
  language = "Py"
  salary = 1200000

  def getInfo(self):
    print(f"The salary is {self.salary} and the language is {self.language}")

@staticmethod
  def greet():
    print("Hello")

harry = Employee()
#harry.language = "C++"
#print(harry.language, harry.salary)
#Employee.getInfo(harry)
harry.greet()
harry.getInfo()

class Employee:
  language = "Py"
  salary = 1200000

  def __init__(self, name, salary, language):         #dunder method which gets automatically called
     print("I am creating an object.")
     self.name = name
     self.salary = salary
     self.language = language

  def getInfo(self):
    print(f"The salary is {self.salary} and the language is {self.language}")

  @staticmethod               #It is a decorater used to prevent self argument
  def greet():
    print("Hello")

harry = Employee("Harry", 1300000, "Javascript")
harry.greet()
harry.getInfo()

"""## **Practice set**"""

class Programmer:
    company = "Microsoft"

    def __init__(self, name, salary, pin):
        self.name = name
        self.salary = salary
        self.pin = pin

p = Programmer("Tam", 1250000, 220005)
print(p.name, p.salary, p.pin, p.company)
q = Programmer("Stacey", 1200000, 220017)
print(q.name, q.salary, q.pin, q.company)
r = Programmer("Loralai", 1250000, 220003)
print(r.name, r.salary, r.pin, r.company)

class Calculator:
    def __init__(self, n):
      self.n = n

    def square(self):
      print(f"The square is {self.n*self.n}.")

    def cube(self):
      print(f"The cube is {self.n*self.n*self.n}.")

    def squareroot(self):
      print(f"The square is {self.n**1/2}.")


a = Calculator(5)
a.square()
a.cube()
a.squareroot()



class Meme:
    a = 50
o = Meme()
print(o.a)       #prints class attribute
o.a = 0          #instance attribute is set
print(o.a)       #prints instance attribute
print(Meme.a)

#Therefore, it can be proved that class attribute does not change

class Calculator:
    def __init__(self, n):
      self.n = n

    def square(self):
      print(f"The square is {self.n*self.n}.")

    def cube(self):
      print(f"The cube is {self.n*self.n*self.n}.")

    def squareroot(self):
      print(f"The square is {self.n**1/2}.")

    @staticmethod
    def greet():
      print("Hello!")


a = Calculator(5)
a.greet()
a.square()
a.cube()
a.squareroot()

import random

class Train():

  def __init__(self, TrainNo):
    self.TrainNo = TrainNo

  def book(self, fro, to):
    print(f"Ticket is booked in train no.: {self.TrainNo} from {fro} to {to}")

  def getStatus(self):
    print(f"Train no.: {self.TrainNo} is running on time")

  def getFare(self, fro, to):
    print(f"Ticket fare in train no.: {self.TrainNo} from {fro} to {to} is {random.randint(250,5500)}")

t = Train(22458)
t.book("Delhi", "Mumbai")
t.getStatus()
t.getFare("Delhi", "Mumbai")